# Generated by Django 5.2 on 2025-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
